apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: sample-app
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: frontend
        image: 319965386003.dkr.ecr.us-east-2.amazonaws.com/sample-app3tier:latest
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://a203c3ee29e64487f8bbf0d2f2912170-462311817.us-east-2.elb.amazonaws.com:3500/api/tasks"
        ports:
        - containerPort: 3000
